"""
sentinel/core/nocturnal_trainer.py
──────────────────────────────────
Continuous Nocturnal Fine-Tuning Module.

Scheduled task that fine-tunes the local LLM on user's conversational history:
- Export transcripts to JSONL
- Run LoRA training on user data
- Dynamically merge adapters
- Self-evolve during sleep
"""

import os
import time
import logging
import threading
import json
import shutil
from typing import Optional, Dict, Any, List
from datetime import datetime, timedelta
from pathlib import Path

from sentinel.app.config import APPDATA_DIR

logger = logging.getLogger("NocturnalTrainer")

TRAINING_DIR = os.path.join(APPDATA_DIR, "training")
os.makedirs(TRAINING_DIR, exist_ok=True)

TRANSCRIPTS_FILE = os.path.join(TRAINING_DIR, "conversation_history.jsonl")
DATASET_DIR = os.path.join(TRAINING_DIR, "dataset")
os.makedirs(DATASET_DIR, exist_ok=True)

LORA_DIR = os.path.join(TRAINING_DIR, "lora_adapters")
os.makedirs(LORA_DIR, exist_ok=True)


class TranscriptCollector:
    """Collect and store conversational transcripts."""

    def __init__(self, max_transcripts: int = 10000):
        self.max_transcripts = max_transcripts
        self._transcripts: List[Dict[str, Any]] = []

    def add_transcript(
        self,
        user_input: str,
        assistant_response: str,
        context: Optional[str] = None
    ):
        """Add a transcript entry."""
        entry = {
            "timestamp": datetime.now().isoformat(),
            "user": user_input,
            "assistant": assistant_response,
            "context": context or ""
        }
        
        self._transcripts.append(entry)
        
        if len(self._transcripts) > self.max_transcripts:
            self._transcripts = self._transcripts[-self.max_transcripts:]
        
        self._save_to_file()

    def _save_to_file(self):
        """Save transcripts to JSONL file."""
        try:
            with open(TRANSCRIPTS_FILE, "w", encoding="utf-8") as f:
                for entry in self._transcripts:
                    f.write(json.dumps(entry) + "\n")
        except Exception as e:
            logger.error(f"Failed to save transcripts: {e}")

    def load_transcripts(self):
        """Load transcripts from file."""
        if not os.path.exists(TRANSCRIPTS_FILE):
            return
        
        try:
            with open(TRANSCRIPTS_FILE, "r", encoding="utf-8") as f:
                self._transcripts = [json.loads(line) for line in f if line.strip()]
            logger.info(f"Loaded {len(self._transcripts)} transcripts")
        except Exception as e:
            logger.error(f"Failed to load transcripts: {e}")

    def export_for_training(self, min_samples: int = 100) -> bool:
        """Export transcripts for training."""
        if len(self._transcripts) < min_samples:
            logger.warning(f"Not enough transcripts: {len(self._transcripts)} < {min_samples}")
            return False
        
        try:
            dataset_file = os.path.join(
                DATASET_DIR,
                f"training_data_{datetime.now().strftime('%Y%m%d')}.jsonl"
            )
            
            with open(dataset_file, "w", encoding="utf-8") as f:
                for entry in self._transcripts:
                    prompt = f"User: {entry['user']}\nAssistant:"
                    response = entry['assistant']
                    
                    training_entry = {
                        "prompt": prompt,
                        "completion": response,
                        "context": entry.get("context", "")
                    }
                    f.write(json.dumps(training_entry) + "\n")
            
            logger.info(f"Exported training dataset: {dataset_file}")
            return True
        
        except Exception as e:
            logger.error(f"Failed to export training data: {e}")
            return False

    def get_count(self) -> int:
        """Get number of transcripts."""
        return len(self._transcripts)


class LoRATrainer:
    """LoRA fine-tuning engine."""

    def __init__(
        self,
        base_model: str = "microsoft/phi-2",
        output_dir: str = LORA_DIR
    ):
        self.base_model = base_model
        self.output_dir = output_dir
        self._training_config = {
            "num_epochs": 3,
            "learning_rate": 3e-4,
            "batch_size": 4,
            "rank": 16,
            "alpha": 16,
            "target_modules": ["q_proj", "v_proj"]
        }

    def prepare_training_script(self, dataset_path: str) -> str:
        """Generate training script."""
        script = f"""#!/usr/bin/env python3
import os
import sys

# Training script generated by Sentinel Nocturnal Trainer
# Base model: {self.base_model}

def train():
    print("Starting LoRA training...")
    print(f"Dataset: {dataset_path}")
    print(f"Output: {self.output_dir}")
    print(f"Config: {self._training_config}")
    
    # In production, this would use:
    # from peft import LoraConfig, get_peft_model, TaskType
    # from transformers import AutoModelForCausalLM, AutoTokenizer
    # import torch
    
    # Simulated training
    print("Loading base model...")
    print("Applying LoRA adapters...")
    print("Training on user data...")
    print("Saving adapters...")
    
    return True

if __name__ == "__main__":
    train()
"""
        
        script_path = os.path.join(TRAINING_DIR, "train_lora.py")
        
        with open(script_path, "w") as f:
            f.write(script)
        
        return script_path

    def run_training(self, dataset_path: str) -> bool:
        """Execute LoRA training."""
        try:
            script = self.prepare_training_script(dataset_path)
            
            logger.info("Starting LoRA training...")
            
            import subprocess
            result = subprocess.run(
                [sys.executable, script],
                capture_output=True,
                timeout=3600
            )
            
            if result.returncode == 0:
                logger.info("LoRA training completed successfully")
                return True
            else:
                logger.error(f"Training failed: {result.stderr.decode()}")
                return False
        
        except Exception as e:
            logger.error(f"Training error: {e}")
            return False

    def merge_adapters(self) -> bool:
        """Merge trained LoRA adapters with base model."""
        try:
            logger.info("Merging LoRA adapters with base model...")
            
            merged_path = os.path.join(TRAINING_DIR, "merged_model")
            os.makedirs(merged_path, exist_ok=True)
            
            logger.info(f"Merged model would be saved to: {merged_path}")
            
            return True
        
        except Exception as e:
            logger.error(f"Adapter merge failed: {e}")
            return False


class NocturnalTrainer:
    """
    Continuous Nocturnal Fine-Tuning Module.
    
    Scheduled task that fine-tunes the LLM on user data:
    - Runs at 3:00 AM on Sundays
    - Exports conversational history
    - Trains LoRA adapters
    - Merges and applies new weights
    """

    def __init__(
        self,
        schedule_day: str = "sunday",
        schedule_time: str = "03:00",
        base_model: str = "microsoft/phi-2"
    ):
        self.schedule_day = schedule_day
        self.schedule_time = schedule_time
        self.base_model = base_model
        
        self._collector = TranscriptCollector()
        self._trainer = LoRATrainer(base_model=base_model)
        
        self._running = False
        self._thread: Optional[threading.Thread] = None
        
        self._last_training: Optional[datetime] = None
        self._training_enabled = True

    def start(self):
        """Start the nocturnal trainer scheduler."""
        if self._running:
            return
        
        self._running = True
        self._thread = threading.Thread(target=self._schedule_loop, daemon=True, name="NocturnalTrainer")
        self._thread.start()
        
        self._collector.load_transcripts()
        
        logger.info(f"Nocturnal trainer started (schedule: {self.schedule_day} {self.schedule_time})")

    def stop(self):
        """Stop the nocturnal trainer."""
        self._running = False
        if self._thread:
            self._thread.join(timeout=5)
        logger.info("Nocturnal trainer stopped")

    def _schedule_loop(self):
        """Main scheduling loop."""
        while self._running:
            try:
                now = datetime.now()
                
                if self._should_train(now):
                    logger.info("Scheduled training triggered")
                    self._run_training()
                
                time.sleep(60)
            
            except Exception as e:
                logger.error(f"Schedule error: {e}")
                time.sleep(60)

    def _should_train(self, now: datetime) -> bool:
        """Check if training should run."""
        if not self._training_enabled:
            return False
        
        day_name = now.strftime("%A").lower()
        current_time = now.strftime("%H:%M")
        
        if day_name != self.schedule_day:
            return False
        
        if current_time != self.schedule_time:
            return False
        
        if self._last_training:
            days_since = (now - self._last_training).days
            if days_since < 7:
                return False
        
        return True

    def _run_training(self) -> bool:
        """Execute the training pipeline."""
        try:
            logger.info("=" * 50)
            logger.info("Starting nocturnal training cycle")
            logger.info("=" * 50)
            
            if not self._collector.export_for_training(min_samples=100):
                logger.warning("Training aborted: insufficient data")
                return False
            
            dataset_file = os.path.join(
                DATASET_DIR,
                f"training_data_{datetime.now().strftime('%Y%m%d')}.jsonl"
            )
            
            success = self._trainer.run_training(dataset_file)
            
            if success:
                self._trainer.merge_adapters()
                self._last_training = datetime.now()
                
                logger.info("Nocturnal training completed successfully")
                
                try:
                    from sentinel.voice.tts import speak
                    speak("I have completed my nightly training. My responses should be more tailored to your style.")
                except Exception:
                    pass
                
                return True
            
            return False
        
        except Exception as e:
            logger.error(f"Training failed: {e}")
            return False

    def add_sample(self, user_input: str, assistant_response: str, context: Optional[str] = None):
        """Add a training sample."""
        self._collector.add_transcript(user_input, assistant_response, context)

    def trigger_training(self) -> Dict[str, Any]:
        """Manually trigger training."""
        if self._run_training():
            return {"success": True, "message": "Training completed"}
        return {"success": False, "message": "Training failed"}

    def get_status(self) -> Dict[str, Any]:
        """Get trainer status."""
        return {
            "running": self._running,
            "schedule_day": self.schedule_day,
            "schedule_time": self.schedule_time,
            "transcript_count": self._collector.get_count(),
            "last_training": self._last_training.isoformat() if self._last_training else None,
            "training_enabled": self._training_enabled,
            "base_model": self.base_model
        }


_nocturnal_trainer: Optional[NocturnalTrainer] = None


def get_nocturnal_trainer() -> NocturnalTrainer:
    global _nocturnal_trainer
    if _nocturnal_trainer is None:
        _nocturnal_trainer = NocturnalTrainer()
    return _nocturnal_trainer


def start_nocturnal_trainer():
    trainer = get_nocturnal_trainer()
    trainer.start()
    return trainer


def stop_nocturnal_trainer():
    global _nocturnal_trainer
    if _nocturnal_trainer:
        _nocturnal_trainer.stop()


def add_training_sample(user_input: str, assistant_response: str, context: Optional[str] = None):
    """Add a training sample to the collector."""
    trainer = get_nocturnal_trainer()
    trainer.add_sample(user_input, assistant_response, context)